//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyTitleAttribute("Yunzhi.Caching.Extensions")]
[assembly: AssemblyProductAttribute("Yunzhi.Caching.Extensions")]
[assembly: AssemblyCompanyAttribute("赣州云智科技有限责任公司")]
[assembly: AssemblyDescriptionAttribute("一个基于LiteDB的数据缓存提供程序，可以同一主机内跨进程共享数据。")]
[assembly: AssemblyCopyright("© 赣州云智科技有限责任公司 2019-2021")]
[assembly: AssemblyVersionAttribute("1.0.*")]
[assembly: AssemblyInformationalVersionAttribute("beta2")]

// 由 MSBuild WriteCodeFragment 类生成。

